spring:
  application:
    name: central
  config:
    import:
      - optional:classpath:/application-dev.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/central
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true

  main:
    banner-mode: off

logging:
  file:
    name: ./log/central.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB
      clean-history-on-start: true
      file-name-pattern: ./log/archive/central-%d{yyyy-MM-dd}.%i.log
  level:
    root: INFO
