token = "12345678"
gh_secret = "12345678"

log_level = 20 # INFO

[central]
endpoint = "http://127.0.0.1:8000"
bearer_token = "12345678"
min_donate_tier_wl = 2

donate_gives_server_types = ["prime", "devtest"]

boosty_discord_id = 12345678

[central.server_types]
# server_type = discord_role_id
prime = 12345678
devtest = 12345678

[central.donation_roles]
# Discord role id from boosty to donate tier
1338876305554542644 = 1
1338876331735121924 = 2


[db]
paradise = {type = "mysql", user = "paradise", password = "paradise", ip = "127.0.0.1", port = 3306, name = "paradise_gamedb"}

[our_servers.SS13.Test]
build = "paradise"
ip = "127.0.0.1"
port = 7777
key = "12345678"

[discord]
# guild id
guild = 12345678
# coder discord id
coder = 12345678

[discord.mentions]
# coder discord id
coder = 12345678
wiki = [12345678, 12345678]

[discord.roles]
heads = [
  12345678,
  12345678,
  12345678,
]
prime_admins = [
  12345678 # Prime Admin
]
admins = [
  12345678, # Admin
  12345678  # Admin new
]
mentors = [
  12345678,
]
devs = [
  12345678,
  12345678,
]

xenomod = [
  12345678,
  12345678,
]

[discord.roles.servers]
Paradise = 12345678
Prime = 12345678

[discord.channels]
spam = 12345678
ban = 12345678
changelog = 12345678
news = 12345678

[redis]
connection_string = "redis://127.0.0.1:6379/0"

[discord.redis]
news_delay = 1200


[changelog]

[changelog.paradise]
repo_id=12345678 # ss220club/Paradise-SS220
discord_webhook="https://discord.com/api/webhooks/12345678/12345678"

[changelog.paradise.valid_tags]
fix="fix"
fixes="fix"
bugfix="fix"
wip="wip"
tweak="tweak"
tweaks="tweak"
rsctweak="tweak"
soundadd="soundadd"
sounddel="sounddel"
imageadd="imageadd"
imagedel="imagedel"
add="codeadd"
adds="codeadd"
rscadd="codeadd"
codeadd="codeadd"
del="codedel"
dels="codedel"
rscdel="codedel"
codedel="codedel"
typo="spellcheck"
spellcheck="spellcheck"
experimental="experiment"
experiment="experiment"

[changelog.paradise.emojified_tags]
soundadd=":notes:"
sounddel=":mute:"
imageadd=":frame_photo:"
imagedel=":scissors:"
codeadd=":sparkles:"
codedel=":wastebasket:"
tweak=":screwdriver:"
fix=":tools:"
wip=":construction_site:"
spellcheck=":pencil:"
experiment=":microscope:"

[workflow]

[workflow.paradise]
repo_id=12345678
ref="master"
app_id="12345678"
private_key_source="private-key.pem"
installation_id="12345678"
merge_upstream="merge_upstream.yml"
