spring:
  application:
    name: ss220-manager
    revision: snapshot
  config:
    import: optional:classpath:/application-dev.yml
  datasource:
    persistence:
      url: jdbc:h2:./ss220manager-database;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
      username:
      password:
      driver-class-name: org.h2.Driver
    paradise:
      url: jdbc:mariadb://localhost:3306/paradise
      username: root
      password: password
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

botcommands:
  application:
    forceGuildCommands: true
  components:
    enable: true

application:
  token: example_bot_token
  profile:
    name: SS220 Manager
    avatar: classpath:images/profile.png
  api:
    central:
      endpoint: http://localhost:8080
      token: example_central_token

logging:
  errorDispatchChannelId: 0
  level:
    root: INFO
    club.ss220.manager: DEBUG
    org.springframework: INFO
    net.dv8tion.jda: INFO
