spring:
  application:
    name: ss220-manager
    revision: snapshot
  config:
    import:
      - classpath:bandastation/roles.yml
      - optional:classpath:/application-dev.yml
  datasource:
    persistence:
      url: jdbc:h2:./app-database;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
      username:
      password:
    paradise:
      url: jdbc:mariadb://localhost:3306/paradise
      username: root
      password: password
    bandastation:
      url: jdbc:mariadb://localhost:3307/bandastation
      username: root
      password: password
  jpa:
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: off

botcommands:
  application:
    forceGuildCommands: true
  components:
    enable: true
  app:
    emojis:
      enable: true

application:
  token: example_bot_token
  profile:
    name: SS220 Manager
    avatar: classpath:images/profile.png
  api:
    central:
      endpoint: http://localhost:8080
      token: example_central_token

logging:
  file:
    name: ./log/manager.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB
      clean-history-on-start: true
      file-name-pattern: ./log/archive/manager-%d{yyyy-MM-dd}.%i.log
  level:
    root: INFO
  discord:
    dispatchChannelId: 0
    dispatchInterval: 10
