name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install flake8
      - name: Run syntax check
        run: flake8 --select=E,W --ignore=E501,W503 src

  run-tests:
    name: Run Tests
    needs: [ syntax-check ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install MariaDB
        run: sudo apt-get install libmariadb-dev
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: PYTHONPATH=${{ github.workspace }}/src python -m unittest discover src/_test
